test_format = 1.0

[default]


    # ------------
    # Tests to run
    # ------------

    exclude = ["change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    test_upgrade_from.471473ef250f28fdc8697824326fb04a82a58d58.name = "Upgrade from 26.5.3~ynh4"

