test_format = 1.0

[default]


    # ------------
    # Tests to run
    # ------------

    exclude = ["change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    test_upgrade_from.e63fc23c82170d2699f3c2761f5241378510fecd.name = "Upgrade from 26.2.14.1~ynh1"

