#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent; 
location __PATH__/ {

	alias __INSTALL_DIR__/;

	# Rewrite to front controller as default rule.
	if (!-e $request_filename) {
		rewrite ^(?<req>.*)$ /index.php?req=$req;
	}

	client_max_body_size 50m;
	client_body_buffer_size 128k;

	# Default indexes and catch-all
	index  index.php;
	charset utf-8;

	location ~* \.php$ {
		try_files $uri =404;
		fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
		include fastcgi_params_no_auth;
		fastcgi_read_timeout 300;
	}

	# Disable access to all existing dotfiles/directories except for .well-known
	# by redirecting them through the router - which will have no existing route or exception for them.
	location ^~ /.well-known/ {
		allow all;
		rewrite ^(?<req>.*)$ /index.php?req=$req;
	}

	location ~ /\. {
		allow all;
		rewrite ^(?<req>.*)$ /index.php?req=$req;
	}

	# block these file types
	location ~* \.(out|log|gz|env|local|yml|yaml|dist)$ {
		allow all;
		rewrite ^(?<req>.*)$ /index.php?req=$req;
	}

	# Deny access to folders no one needs to have access to
	location ~ ^/(bin|cache|config|src|store|templates|util) {
		allow all;
		rewrite ^(?<req>.*)$ /index.php?req=$req;
	}

	# Deny access to folders we don’t have a use for
	location ~ ^/(contrib|tests) {
		allow all;
		rewrite ^(?<req>.*)$ /index.php?req=$req;
	}

	# Deny access to files no one needs to see and don’t start with a dot
	location ~ ^/(env|phpunit\.xml) {
		allow all;
		rewrite ^(?<req>.*)$ /index.php?req=$req;
	}

	# Deny access to vendor except for required folders and extensions
	location ~ ^/vendor/(?!(.*/fonts|.*\.(js|php|css))) {
		allow all;
		rewrite ^(?<req>.*)$ /index.php?req=$req;
	}

	# Deny access to composer related files in base directory
	location ~* ^/(compose\.|composer\.) {
		allow all;
		rewrite ^(?<req>.*)$ /index.php?req=$req;
	}

	# Deny access to *.tpl files in view
	location ~ ^/view/tpl/.*\.tpl$ {
		allow all;
		rewrite ^(?<req>.*)$ /index.php?req=$req;
	}
}
