#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

php_version="$YNH_PHP_VERSION"

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

ynh_app_config_validate() {
    _ynh_app_config_validate
}

ynh_app_config_apply() {
    _ynh_app_config_apply
}

ynh_app_config_run $1
