#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

phpversion="$YNH_PHP_VERSION"
current_fpm_footprint=$(ynh_app_setting_get --app=$app --key=fpm_footprint)

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__git_branch_mode() {
    # Maintenance mode status
    git_branch_mode_status="$(cd "$install_dir" && git branch --show-current)" 2> /dev/null
    if echo $git_branch_mode_status | grep -q "release"
    then
        echo "0"
    elif echo $git_branch_mode_status | grep -q "dev"
    then
        echo "1"
    else
        ynh_print_err --message="Not using \"release\" or \"dev\" branch, please handle this in command line"
        exit 0
    fi
}

get__fpm_footprint() {
    # Free footprint value for php-fpm
    # Check if current_fpm_footprint is an integer
    if [ "$current_fpm_footprint" -eq "$current_fpm_footprint" ] 2> /dev/null
    then
        echo "specific"
    else
        echo "$current_fpm_footprint"
    fi
}

get__free_footprint() {
    # Free footprint value for php-fpm
    # Check if current_fpm_footprint is an integer
    if [ "$current_fpm_footprint" -eq "$current_fpm_footprint" ] 2> /dev/null
    then
        # If current_fpm_footprint is an integer, that's a numeric value for the footprint
        echo "$current_fpm_footprint"
    else
        echo "0"
    fi
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================


set__git_branch_mode() {
    if [ "$git_branch_mode" -eq "0" ]
    then
        # We allow switch back to "release" only if the branch is ahead of "dev"
        if [ -z "$(cd "$install_dir" && git log --oneline release..dev)" ]
        then
            # If git_branch was set to 0, switch to "release" branch
            ynh_print_info "Switching to \"release\" branch"
            (cd "$install_dir" && ynh_exec_as "$app" git checkout release)
            ynh_print_info "Full update of the website"
            (cd "$install_dir" && ynh_exec_as "$app" util/udall)
        else
            ynh_die --message="\"release\" branch is behind your local \"dev\" branch, rolling back is not allowed here"
            exit 1
        fi
    elif [ "$git_branch_mode" -eq "1" ]; then
        # If git_branch was set to 1, switch to "dev" branch
        (cd "$install_dir" && ynh_exec_as "$app" git checkout dev)
        ynh_print_info "Switching to \"dev\" branch"
    fi
    ynh_app_setting_set --app=$app --key=git_branch_mode --value="$git_branch_mode"
}

set__fpm_footprint() {
    if [ "$fpm_footprint" != "specific" ]
    then
        ynh_app_setting_set --app=$app --key=fpm_footprint --value="$fpm_footprint"
    fi
}

set__fpm_free_footprint() {
    if [ "$fpm_footprint" = "specific" ]
    then
        ynh_app_setting_set --app=$app --key=fpm_footprint --value="$fpm_free_footprint"
    fi
}

#=================================================
# GENERIC FINALIZATION
#=================================================

ynh_app_config_validate() {
    _ynh_app_config_validate

    if [ "${changed[fpm_usage]}" == "true" ] || [ "${changed[fpm_footprint]}" == "true" ] || [ "${changed[fpm_free_footprint]}" == "true" ]; then
        # If fpm_footprint is set to 'specific', use $fpm_free_footprint value.
        if [ "$fpm_footprint" = "specific" ]
        then
            fpm_footprint=$fpm_free_footprint
        fi

        if [ "$fpm_footprint" == "0" ]
        then
            ynh_print_err --message="When selecting 'specific', you have to set a footprint value into the field below."

            exit 0
        fi
    fi
}

ynh_app_config_apply() {
    _ynh_app_config_apply

    ynh_add_fpm_config --phpversion=$phpversion --usage=$fpm_usage --footprint=$fpm_footprint
}

ynh_app_config_run $1
