#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

email=$(ynh_user_get_info --username=$admin --key=mail)
upload="256M"
random_string="$(ynh_string_random --length=48)"
#REMOVEME? Everything about fpm_footprint is removed in helpers2.1... | fpm_footprint="medium"
#REMOVEME? Everything about fpm_free_footprint is removed in helpers2.1... | fpm_free_footprint=0
#REMOVEME? Everything about fpm_usage is removed in helpers2.1... | fpm_usage="medium"
git_branch_mode="0"

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression "Storing installation settings..."

ynh_app_setting_set --key=email --value=$email
ynh_app_setting_set --key=upload --value=$upload
ynh_app_setting_set --key=random_string --value=$random_string
#REMOVEME? Everything about fpm_footprint is removed in helpers2.1... | ynh_app_setting_set --key=fpm_footprint --value=$fpm_footprint
#REMOVEME? Everything about fpm_free_footprint is removed in helpers2.1... | ynh_app_setting_set --key=fpm_free_footprint --value=$fpm_free_footprint
#REMOVEME? Everything about fpm_usage is removed in helpers2.1... | ynh_app_setting_set --key=fpm_usage --value=$fpm_usage
ynh_app_setting_set --key=git_branch_mode --value="$git_branch_mode"

#=================================================
# CREATE A DATABASE
#=================================================
ynh_script_progression "Creating a database..."

ynh_mysql_db_shell \
<<< "ALTER DATABASE $db_name CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

mkdir -p "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
# Download, check integrity, uncompress and patch the source from GitHub
ynh_exec_as_app git clone https://codeberg.org/streams/streams.git "$install_dir" --quiet
git config --system --add safe.directory $install_dir

touch "$install_dir/php.log"
mkdir -p "$install_dir/store"
mkdir -p  "$install_dir/cache/smarty3"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
chmod -R 775 $install_dir/store $install_dir/cache

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Configuring PHP-FPM..."

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# COMPOSER
#=================================================
ynh_script_progression "Pulling in external libraries with Composer..."

ynh_composer_install
ynh_composer_exec install --no-dev

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# ADDONS
#=================================================
ynh_script_progression "Installing addons..."

pushd $install_dir
    ynh_exec_as_app git config pull.rebase false
    ynh_exec_as_app util/add_addon_repo https://codeberg.org/streams/streams-addons.git zaddons
    cd /var/www/$app/extend/addon/zaddons
    ynh_exec_as_app git config pull.rebase false
popd

#=================================================
# SPECIFIC SETUP
#=================================================
# PROVISION DATABASE
#=================================================
ynh_script_progression "Provisionning database..."

ynh_mysql_db_shell < $install_dir/install/schema_mysql.sql

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

timezone=$(</etc/timezone)

if [ $activate_directory -eq 1 ]
then
    max_imported_follow=10
else
    max_imported_follow=0
fi

ynh_config_add --template="htconfig.sample.php" --destination="$install_dir/.htconfig.php"

ynh_store_file_checksum $install_dir/.htconfig.php

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 600 "$install_dir/.htconfig.php"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:$app "$install_dir/.htconfig.php"

ynh_exec_as_app touch $data_dir/extra_conf.php

#=================================================
# SET CRON JOBS
#=================================================
ynh_script_progression "Setuping cron job..."

# Set up cron job
ynh_config_add --template="cronjobs" --destination="/etc/cron.d/$app"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown root: "/etc/cron.d/$app"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 644 "/etc/cron.d/$app"
# Add daily update script
ynh_config_add --template="daily-update.sh" --destination="/home/yunohost.app/$app/daily-update.sh"
chown root: "/home/yunohost.app/$app/daily-update.sh"

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression "Configuring log rotation..."

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate "$install_dir/php.log"

#=================================================
# SETUP FAIL2BAN
#=================================================
ynh_script_progression "Configuring Fail2Ban..."

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="$install_dir/php.log" --failregex="^.*auth\.php.*failed login attempt.*from IP <HOST>.*$"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
