#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the dedicated PHP-FPM config
ynh_config_remove_phpfpm

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

# Remove the dedicated Fail2Ban config
ynh_config_remove_fail2ban

# Remove a cron file
ynh_safe_rm "/etc/cron.d/$app"

# Remove daily updates logfile
ynh_safe_rm "$data_dir/daily-updates.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
